# sstorm-rectest auto-configuration
#
# When enable_autoconfigure is true, the tool will query InfluxDB
# for cell parameters observed by the sni5gect-compact shadower
# and generate enb.conf, ue.conf, rr.conf, and sib.conf automatically.

enable_autoconfigure: true

influxdb:
  host: "0.0.0.0"
  port: 8086
  org: "rtu"
  token: "605bc59413b7d5457d181ccf20f9fda15693f81b068d70396cc183081b264f3b"
  bucket: "rtusystem"
  data_id: "test"
