[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
s1c_bind_port = 0
n_prb = 50

[enb_files]
sib_config = sib.conf
rr_config  = rr.conf
rb_config = rb.conf

[rf]
tx_gain = 80
rx_gain = 40
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6

[log]
all_level = warning
all_hex_limit = 32
filename = /tmp/enb.log
file_max_size = -1

[gui]
enable = false

[pcap]
enable = false
s1ap_enable = false

[scheduler]
policy = time_pf

[expert]
metrics_period_secs = 1
metrics_csv_enable = false

[recon]
enable = true
host = localhost
port = 8086
org = rtu
token = 605bc59413b7d5457d181ccf20f9fda15693f81b068d70396cc183081b264f3b
bucket = rtusystem
data_id = generic_zmq
